### ISSUE TITLE
Add scope to learning objectives, and add content about scope

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/js-functions-ins-and-outs#26]
A lot of this lesson would make more sense if students had a basic understanding of what scope is. I remember my cohort (009) having a lesson on scope, but it doesn't seem to be included now. I think adding a basic intro to scope in a study or as part of this lesson would be very helpful.

**Comment by gaand** [comment]
@jrhorn424 Thoughts?  I think @raq929 makes a good point.  We should dwell on it, but some links a brief discussion seems sensible.

**Comment by raq929** [comment]
I think you meant we shouldn't dwell on it. ;)

**Comment by gaand** [comment]
I think you're right :robot: :heavy_multiplication_x: 

Corrected below

``` diff
-We should dwell on it, but some links a brief discussion seems sensible.
+We shouldn't dwell on it, but some links and a brief discussion seems sensible.
```

**Comment by jrhorn424** [comment]
@gaand @ga-wdi-boston/core I agree that `scope` is most accurately covered at this point in the curriculum. It should be added as a learning objective and appropriate prose/example code/exercises added. I'll see if I can find some collateral from old repos (I made a few diagrams at some point).

**Comment by jrhorn424** [comment]
![scope](https://media.giphy.com/media/l0MYvbCWACoAqOUaA/giphy.gif)
