### ISSUE TITLE
Did we lose a solution or demo branch?

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js-functions-ins-and-outs#30]
@ga-wdi-boston/core Anyone have a downstream branch that should be promoted to upstream?

**Comment by gaand** [comment]
Maybe?

**Comment by gaand** [comment]
https://github.com/gaand/js-functions-ins-and-outs/tree/015/training

**Comment by jrhorn424** [comment]
cc @MicFin

**Comment by jrhorn424** [comment]
Closing in favor of #17
