### ISSUE TITLE
Code along example is broken

### ISSUE THREAD

**Issue by MicFin** [ga-wdi-boston/js-functions-ins-and-outs#48]
This example may be incorrect to show error and then fix but it is not clear.
https://github.com/ga-wdi-boston/js-functions-ins-and-outs#code-along---return-new-functions
```diff
- const memoFactory = function (memo) {
+ const memoFactory = function () {
  let total = 0

-  return function () {
+  return function (memo) {
    total+= 1
    return total + ": " + memo
  }
}
```

**Comment by jrhorn424** [comment]
Closing, since I accidentally provided more detail over in #49
